# Generated by Django 5.2.8 on 2025-11-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_studentprofile_active_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_quiz_upload_notifications', models.BooleanField(default=True, help_text='Send email notifications when a new quiz is uploaded')),
                ('enable_submission_notifications', models.BooleanField(default=True, help_text='Send email notifications when a student submits a quiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Notification Settings',
                'verbose_name_plural': 'Email Notification Settings',
            },
        ),
    ]
