# Generated by Django 5.2.8 on 2025-11-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_pinattempttracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinAttemptTracker',
        ),
    ]
