# Generated by Django 5.2.8 on 2025-11-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_emailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='enable_student_registration_notifications',
            field=models.BooleanField(default=True, help_text='Send email notifications when a student is registered'),
        ),
    ]
